config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#homepage'
  get 'about', to: 'pages#about'
  get 'article_news', to: 'articles#new'
  get 'author_new', to: 'authors#new'

  resources :articles
  resources :authors

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :description, presence: true, length: {minimum: 10, maximum: 300}

end

app/models/author.rb
class Author < ApplicationRecord
  validates :first_name, presence: true, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }
  validates :last_name, presence: true, format: { with: /\A[a-zA-Z]+\z/, message: "only allows letters" }
  validates :email_address, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:edit, :show, :destroy, :update]
  def index
    @articles = Article.all
  end

  def new
    @article = Article.new
  end

  def create
    #render plain: params[:article].inspect
    @article = Article.new(article_params)
    if @article.save
      flash[:notice] = "Article was saved successfully"
      redirect_to article_path(@article)
    else
      render 'new'
      #redirect_to about_path
    end
  end

  def show

  end

  def edit

  end

  def destroy
    @article.destroy
    flash[:notice] = "Article was deleted successfully"
    redirect_to articles_path
  end

  def update
    if @article.update(article_params)
      flash[:notice] = "Article has been updated successfully"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end

  private

    def set_article
      @article = Article.find(params[:id])
    end

    def article_params
      params.require(:article).permit(:title, :description)
    end
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def new
    @author = Author.new
  end

  def create
    @author = Author.new(author_params)
    @author.save
  end

  private
    def author_params
      params.require(:author).permit(:first_name, :last_name, :email_address)
    end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def homepage

  end

  def about

  end
end 

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_form.html.erb
  <% if @article.errors.any? %>
    <p>The following errors prevented the article from getting created</p>
    <ul>
      <% @article.errors.full_messages.each do |msg| %>
        <li class="error_msg"><%= msg %></li>
      <% end %>
    </ul>
<% end %>
  <%= form_for @article do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title%>
  </p>
  <p>
    <%= f.label :description %><br>
    <%= f.text_area :description%>
  </p>
  <p>
    <%= f.submit "Submit Article" %>
  </p>
  <% end %>
  <%= button_to "Article overview", articles_path, :method => "get" %>

app/views/articles/edit.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="homepage.css">
  <title>Alpha-Blog</title>
</head>
<header>
  <%= render 'pages/top_navigation' %>
  <div class="centered_content">
  <h1 class="page_title">Edit an article</h1>
      <%= render 'form' %>
  </div>
</header>

app/views/articles/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="homepage.css">
  <title>Alpha-Blog</title>
</head>

<header>
  <%= render 'pages/top_navigation' %>
  <div class="centered_content">
    <h1 class="page_title">Listing all articles</h1>
    <br>
    <p> <%= button_to "Create new article", article_news_path, :method => "get" %>
    <br>
      <table>
        <tr>
          <th>Title</th>
          <th>Description</th>
          <th>Edit</th>
        </tr>

        <% @articles.each do |article| %>
        <tr>
          <td><%= article.title %></td>
          <td><%= article.description %></td>
          <td><%= button_to "Edit #{article.id}", edit_article_path(article), :method => "get" %></td>
          <td><%= button_to "Show", article_path(article), :method => "get" %></td>
          <td><%= button_to "Delete", article_path(article), :method => "delete", data: {confirm: "Are you sure?"} %></td>

        </tr>
        <% end %>
      </table>
  </div>
</header>

app/views/articles/new.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="homepage.css">
  <title>Alpha-Blog</title>
</head>
<header>
  <%= render 'pages/top_navigation' %>
  <div class="centered_content">
    <h1 class="page_title">Create an article</h1>
      <%= render 'form' %>
  </div>
</header>

app/views/articles/show.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="homepage.css">
  <title>Alpha-Blog</title>
</head>
<header>
  <%= render 'pages/top_navigation' %>
  <div class="centered_content">
    <h1>Showing selected article</h1>
    <p>
      Title: <%= @article.title %>
    </p>
    <p>
      Description: <%= @article.description %>
    </p>
    <p>
      <%= button_to "Edit Article", edit_article_path(@article), :method => "get" %>
    </p>

    <p>
      <%= button_to "Article overview", articles_path, :method => "get" %>
    </p>
  </div>
</header>

app/views/authors/new.html.erb
<header>
  <h1>Create an Author</h1>

  <%= form_for @author do |f| %>
    <p>
      <%= f.label :firstname %><br>
      <%= f.text_field :first_name%>
    </p>
    <p>
      <%= f.label :lastname %><br>
      <%= f.text_field :last_name%>
    </p>
    <p>
      <%= f.label :email %><br>
      <%= f.text_field :email_address%>
    </p>
    <p>
      <%= f.submit "Submit Author" %>
    </p>

  <% end %>

</header>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <ul>
    <li><%= msg %></li>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
    <%= render 'layouts/messages' %>
    <%= yield %>
  </header>
</html>

app/views/pages/_top_navigation.html.erb
<img id="logo" src="/images/kai_logo.png">
<h1 id="page_header">Kai <br>Nass</h1>
<ul class="header_ul">
  <li class="header_li"><p><%= link_to 'Homepage', root_path %></p></li>
  <li class="header_li"><p><%= link_to 'About', about_path %></p></li>
  <li class="header_li"><a href="#">Imprint</a></li>
</ul>
<hr class="full_line">

app/views/pages/about.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="homepage.css">
  <title>Alpha-Blog</title>
</head>
<body>
    <!-- --------------------------------->
    <header>
      <%= render 'pages/top_navigation'%>

      <div class="header_div">
        <h2>This is your About page.<br>Mate.</h2>
        <p class="btn btn_leer"><%= link_to 'Homepage', root_path %></p>
        <p class="btn btn_leer"><%= link_to 'Artikel', articles_path %></p>
        <p class="btn btn_voll"><%= link_to 'Author', author_new_path %></p>

      </div>
    </header>
    <section>
        <h2>About</h2>
    </section>
</body>

app/views/pages/homepage.html.erb
<!DOCTYPE html>
<html>
<head>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300,700&display=swap" rel="stylesheet">
  <link rel="stylesheet" href="homepage.css">
  <title>Alpha-Blog</title>
</head>
<body>
    <!-- --------------------------------->
    <header>
      <%= render 'top_navigation' %>

      <div class="header_div">
        <h2>This is your Homepage.<br>Mate.</h2>
        <p class="btn btn_voll"><%= link_to 'Artikel', articles_path %></p>
        <p class="btn btn_leer"><%= link_to 'Author', author_new_path %></p>
        <p class="btn btn_leer">Write me</p>
      </div>
    </header>
    <section>
        <h2>HOMEPAGE</h2>
    </section>
</body>